import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { rateLimit } from "express-rate-limit";
import mongoose from "mongoose";
import { env } from "./config/env.js";
import authRoutes from "./routes/auth.js";
import sensorRoutes from "./routes/sensors.js";
import telemetryRoutes from "./routes/telemetry.js";
import analyticsRoutes from "./routes/analytics.js";
import rewardRoutes from "./routes/rewards.js";
import userRoutes from "./routes/users.js";
import { errorHandler, notFound } from "./middleware/errors.js";
import { optionalAuth } from "./middleware/auth.js";

export const app = express();
app.disable("x-powered-by");
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL.split(",").map((value) => value.trim()), credentials: true }));
app.use(express.json({ limit: "32kb" }));
app.use(morgan(env.NODE_ENV === "production" ? "combined" : "tiny"));
app.use("/api", rateLimit({ windowMs: 60_000, limit: 6000, standardHeaders: "draft-7", legacyHeaders: false, message: { success: false, message: "Too many requests. Try again shortly." } }));
app.use("/api/auth", rateLimit({ windowMs: 15 * 60_000, limit: 30, standardHeaders: "draft-7", legacyHeaders: false, message: { success: false, message: "Too many authentication attempts. Try again later." } }));
app.get("/api/health", (_req, res) => res.json({ success: true, message: "BREEZO API is running", services: { database: mongoose.connection.readyState === 1 ? "connected" : "disconnected" }, timestamp: new Date().toISOString() }));
app.use("/api/auth", authRoutes);
app.use("/api/sensors", optionalAuth, sensorRoutes);
app.use("/api/telemetry", telemetryRoutes);
app.use("/api/analytics", analyticsRoutes);
app.use("/api/rewards", optionalAuth, rewardRoutes);
app.use("/api/users", userRoutes);
app.use(notFound);
app.use(errorHandler);
