import { useCallback, useEffect, useState } from "react";
import { Activity, ArrowLeft, Clock3, MapPin, ShieldCheck, Wifi } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { SensorMap } from "../components/SensorMap";
import { demoHistory, demoSensors } from "../data/demo";
import { request } from "../services/api";
import type { SensorData } from "../types/sensor";
import { useSensorSocket } from "../hooks/useSensorSocket";
import { getSocket } from "../services/socket";
type SensorPoint = { timestamp: string; label: string; aqi: number; pm25: number; pm10: number; temperature?: number; humidity?: number };
export default function SensorDetails({ sensorId }: { sensorId: string }) {
  const [sensor, setSensor] = useState<SensorData | null>(null); const [series, setSeries] = useState<SensorPoint[]>(demoHistory()); const [demo, setDemo] = useState(false); const [error, setError] = useState("");
  const onTelemetry = useCallback((reading: SensorData) => { if (reading.sensorId !== sensorId) return; setSensor(reading); setDemo(false); setSeries((current) => [...current.slice(-47), { ...reading, label: new Date(reading.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }]); }, [sensorId]);
  useSensorSocket(onTelemetry);
  useEffect(() => {
    const socket = getSocket();
    const disconnected = (event: { sensorId: string }) => { if (event.sensorId === sensorId) setSensor((current) => current ? { ...current, status: "offline" } : current); };
    socket.on("sensor:disconnected", disconnected);
    return () => { socket.off("sensor:disconnected", disconnected); };
  }, [sensorId]);
  useEffect(() => { let mounted = true; void (async () => { try { const data = await request<SensorData>(`/sensors/${encodeURIComponent(sensorId)}`); if (mounted) { setSensor(data); setDemo(false); } const history = await request<Array<{ timestamp: string; aqi: number; pm25: number; pm10: number; temperature: number; humidity: number }>>(`/telemetry/${encodeURIComponent(sensorId)}?limit=48`); if (mounted && history.length) setSeries(history.map((x) => ({ ...x, label: new Date(x.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }))); } catch (cause) { if (mounted) { const found = demoSensors.find((x) => x.sensorId === sensorId); setSensor(found ?? null); setDemo(Boolean(found)); setError(cause instanceof Error ? cause.message : "API unavailable"); } } })(); return () => { mounted = false; }; }, [sensorId]);
  if (!sensor) return <div className="not-found-panel"><button className="text-action" onClick={() => window.history.back()}><ArrowLeft size={14} /> Back to sensors</button><h1>Sensor not found</h1><p>{error || "This sensor is not registered in the connected API."}</p></div>;
  const charts = [{ title: "Air Quality Index", key: "aqi", color: "#7ce2b2", unit: "AQI" }, { title: "PM2.5 concentration", key: "pm25", color: "#7fbfff", unit: "µg/m³" }, { title: "PM10 concentration", key: "pm10", color: "#c2a2ff", unit: "µg/m³" }, { title: "Temperature", key: "temperature", color: "#e8bd70", unit: "°C" }, { title: "Humidity", key: "humidity", color: "#73c6da", unit: "%" }];
  return <div className="workspace-page"><button className="back-link" onClick={() => window.dispatchEvent(new CustomEvent("breezo:navigate", { detail: "/sensors" }))}><ArrowLeft size={15} /> Sensor fleet</button><div className="page-heading detail-heading"><div><div className="heading-kicker"><span className="kicker-line" /> {sensor.sensorId}</div><h1>{sensor.name ?? sensor.sensorId}</h1><p><MapPin size={14} /> {sensor.location ?? "Location not provided"}</p></div><div className="heading-actions"><span className={`status-label ${sensor.status}`}><i />{sensor.status}</span>{demo && <span className="live-pill demo"><i /> DEMO DATA</span>}</div></div>{demo && <div className="notice notice-demo"><Activity size={15} /><span>Sample sensor profile · illustrative data only</span><small>{error}</small></div>}
    <div className="detail-grid"><section className="panel detail-overview"><div className="panel-heading"><div><span className="eyebrow">CURRENT TELEMETRY</span><h2>Latest reading</h2></div><span className="reading-time"><Clock3 size={13} /> {new Date(sensor.timestamp).toLocaleString()}</span></div><div className="detail-reading-grid"><div className="detail-reading highlight"><span>AQI</span><strong>{sensor.status === "offline" ? "—" : sensor.aqi}</strong><small>{sensor.aqi <= 50 ? "Good" : sensor.aqi <= 100 ? "Moderate" : "Elevated"}</small></div><div className="detail-reading"><span>PM2.5</span><strong>{sensor.status === "offline" ? "—" : sensor.pm25.toFixed(1)}<small>µg/m³</small></strong></div><div className="detail-reading"><span>PM10</span><strong>{sensor.status === "offline" ? "—" : sensor.pm10.toFixed(1)}<small>µg/m³</small></strong></div><div className="detail-reading"><span>Temperature</span><strong>{sensor.status === "offline" ? "—" : sensor.temperature.toFixed(1)}<small>°C</small></strong></div><div className="detail-reading"><span>Humidity</span><strong>{sensor.status === "offline" ? "—" : sensor.humidity}<small>%</small></strong></div></div><div className="provenance-row"><span><Wifi size={14} /> Device status <strong>{sensor.status}</strong></span><span><ShieldCheck size={14} /> Blockchain <strong>{sensor.isVerified ? "Verified" : "Not verified"}</strong></span></div></section><section className="panel detail-map-panel"><div className="panel-heading"><div><span className="eyebrow">LOCATION</span><h2>Node position</h2></div></div><SensorMap sensors={[sensor]} compact /></section></div>
    <section className="detail-charts">{charts.map(({ title, key, color, unit }) => <article className="panel detail-chart" key={key}><div className="panel-heading"><div><span className="eyebrow">LAST 24 HOURS</span><h2>{title}</h2></div><strong className="detail-current">{sensor[key as keyof SensorData] as number} <small>{unit}</small></strong></div><div className="small-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{ top: 8, right: 4, bottom: 0, left: -22 }}><defs><linearGradient id={`fill-${key}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={0.19} /><stop offset="100%" stopColor={color} stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#222927" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#77817d", fontSize: 9 }} axisLine={false} tickLine={false} minTickGap={25} /><YAxis tick={{ fill: "#77817d", fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#101615", border: "1px solid #29312e", borderRadius: 8 }} /><Area type="monotone" dataKey={key} stroke={color} fill={`url(#fill-${key})`} strokeWidth={1.8} /></AreaChart></ResponsiveContainer></div></article>)}</section>
    <section className="panel connection-panel"><div><span className="eyebrow">DEVICE IDENTITY</span><h2>Registration & connectivity</h2><p>Telemetry is authenticated with a per-device secret and sequence number.</p></div><div className="identity-data"><span>Sensor identifier <strong>{sensor.sensorId}</strong></span><span>Owner <strong>{sensor.owner ?? "Not assigned"}</strong></span><span>Blockchain address <strong>{sensor.blockchainAddress ?? "Not linked"}</strong></span></div></section>
  </div>;
}
